version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9
      - image: circleci/mongo:3
      - image: redis:4@sha256:b77926b30ca2f126431e4c2055efcf2891ebd4b4c4a86a53cf85ec3d4c98a4c9
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run lerna bootstrap
      - run: yarn test
      - run: yarn codecov
      - run: cd react-rest-typescript && yarn install --frozen-lockfile && yarn test
      - run: cd rest-express-typescript && yarn install --frozen-lockfile && yarn test
      - run: cd react-graphql-typescript && yarn install --frozen-lockfile && yarn test
      - run: cd graphql-server-typescript && yarn install --frozen-lockfile && yarn test
