blank_issues_enabled: false
contact_links:
  - name: ðŸ™‹ Ask a question
    url: https://github.com/accounts-js/accounts/discussions
    about: Ask questions and discuss with other community members
